# Generated by Django 4.2.4 on 2023-10-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillucketApp', '0002_bucketskill_notes_userskill_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Tell the world about yourself!'),
        ),
    ]
